/** Shared UI dictionary. Korean is primary (ko-KR); English is the toggle. Screen-specific copy uses L(ko, en). */
export const DICT = {
  ko: {
    'nav.stay': '숙소',
    'nav.exchange': '홈 맞교환',
    'nav.guide': '가이드 프렌드',
    'nav.travel': '여행 상품',
    'nav.charter': '전세기 JETPOOL',
    'nav.trips': '내 여행',
    'nav.messages': '메시지',
    'nav.saved': '저장',
    'nav.host': '호스트',
    'nav.admin': '관리자',
    'nav.login': '로그인',
    'nav.signup': '회원가입',
    'nav.logout': '로그아웃',
    'nav.account': '계정',
    'nav.menu': '메뉴',
    'state.loading': '불러오는 중…',
    'state.empty': '아직 항목이 없습니다.',
    'state.error': '문제가 발생했습니다.',
    'state.retry': '다시 시도',
    'state.unauth': '로그인이 필요한 페이지입니다.',
    'state.forbidden': '이 페이지에 접근할 권한이 없습니다.',
    'state.mfa': '관리자 기능은 2단계 인증(MFA) 세션이 필요합니다.',
    'state.mfa.cta': 'MFA 인증하기',
    'state.disabled': '이 기능은 현재 운영 정책에 따라 비활성화되어 있습니다.',
    'state.notfound': '요청한 페이지를 찾을 수 없습니다.',
    'common.search': '검색',
    'common.save': '저장',
    'common.cancel': '취소',
    'common.submit': '제출',
    'common.confirm': '확인',
    'common.more': '더 보기',
    'common.close': '닫기',
    'common.guests': '인원',
    'common.checkin': '체크인',
    'common.checkout': '체크아웃',
    'common.night': '박',
    'common.status': '상태',
    'common.actions': '작업',
    'common.back': '뒤로',
    'common.lang': 'English',
    'footer.rights': '모든 거래 상태는 서버에서 확정됩니다.',
  },
  en: {
    'nav.stay': 'Stays',
    'nav.exchange': 'Home Exchange',
    'nav.guide': 'Guide Friends',
    'nav.travel': 'Travel',
    'nav.charter': 'Charter JETPOOL',
    'nav.trips': 'Trips',
    'nav.messages': 'Messages',
    'nav.saved': 'Saved',
    'nav.host': 'Host',
    'nav.admin': 'Admin',
    'nav.login': 'Log in',
    'nav.signup': 'Sign up',
    'nav.logout': 'Log out',
    'nav.account': 'Account',
    'nav.menu': 'Menu',
    'state.loading': 'Loading…',
    'state.empty': 'Nothing here yet.',
    'state.error': 'Something went wrong.',
    'state.retry': 'Retry',
    'state.unauth': 'Please sign in to view this page.',
    'state.forbidden': 'You do not have access to this page.',
    'state.mfa': 'Admin features require a multi-factor (MFA) session.',
    'state.mfa.cta': 'Verify with MFA',
    'state.disabled': 'This feature is currently disabled by operating policy.',
    'state.notfound': 'Page not found.',
    'common.search': 'Search',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.confirm': 'Confirm',
    'common.more': 'More',
    'common.close': 'Close',
    'common.guests': 'Guests',
    'common.checkin': 'Check-in',
    'common.checkout': 'Check-out',
    'common.night': 'nights',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.back': 'Back',
    'common.lang': '한국어',
    'footer.rights': 'All transaction states are confirmed server-side.',
  },
} as const;

export type DictKey = keyof (typeof DICT)['ko'];
