/**
 * Shared UI dictionary — chrome that appears on every screen (navigation, page states, common verbs).
 * Korean is the source language. Screen-specific copy is written inline as `L(ko, en)` and translated by
 * source string in lib/phrases.ts; this file is for the keys that are referenced symbolically via `t('…')`.
 *
 * Every language is typed `Record<DictKey, string>`, so adding a key fails the typecheck until all five
 * languages have it — no silent gaps in the chrome.
 */
import type { Lang } from './format';

const ko = {
  'nav.stay': '숙소',
  'nav.exchange': '홈 맞교환',
  'nav.guide': '가이드 프렌드',
  'nav.travel': '여행 상품',
  'nav.charter': '전세기 JETPOOL',
  'nav.trips': '내 여행',
  'nav.messages': '메시지',
  'nav.saved': '저장',
  'nav.host': '호스트',
  'nav.admin': '관리자',
  'nav.login': '로그인',
  'nav.signup': '회원가입',
  'nav.logout': '로그아웃',
  'nav.account': '계정',
  'nav.menu': '메뉴',
  'state.loading': '불러오는 중…',
  'state.empty': '아직 항목이 없습니다.',
  'state.error': '문제가 발생했습니다.',
  'state.retry': '다시 시도',
  'state.unauth': '로그인이 필요한 페이지입니다.',
  'state.forbidden': '이 페이지에 접근할 권한이 없습니다.',
  'state.mfa': '관리자 기능은 2단계 인증(MFA) 세션이 필요합니다.',
  'state.mfa.cta': 'MFA 인증하기',
  'state.disabled': '곧 제공될 예정이에요',
  'state.notfound': '요청한 페이지를 찾을 수 없습니다.',
  'common.search': '검색',
  'common.save': '저장',
  'common.cancel': '취소',
  'common.submit': '제출',
  'common.confirm': '확인',
  'common.more': '더 보기',
  'common.close': '닫기',
  'common.guests': '인원',
  'common.checkin': '체크인',
  'common.checkout': '체크아웃',
  'common.night': '박',
  'common.status': '상태',
  'common.actions': '작업',
  'common.back': '뒤로',
  'common.lang': '언어',
  'lang.auto': '브라우저 언어 사용',
  'a11y.skip': '본문 바로가기',
} as const;

export type DictKey = keyof typeof ko;

const en: Record<DictKey, string> = {
  'nav.stay': 'Stays',
  'nav.exchange': 'Home Exchange',
  'nav.guide': 'Guide Friends',
  'nav.travel': 'Travel',
  'nav.charter': 'Charter JETPOOL',
  'nav.trips': 'Trips',
  'nav.messages': 'Messages',
  'nav.saved': 'Saved',
  'nav.host': 'Host',
  'nav.admin': 'Admin',
  'nav.login': 'Log in',
  'nav.signup': 'Sign up',
  'nav.logout': 'Log out',
  'nav.account': 'Account',
  'nav.menu': 'Menu',
  'state.loading': 'Loading…',
  'state.empty': 'Nothing here yet.',
  'state.error': 'Something went wrong.',
  'state.retry': 'Retry',
  'state.unauth': 'Please sign in to view this page.',
  'state.forbidden': 'You do not have access to this page.',
  'state.mfa': 'Admin features require a multi-factor (MFA) session.',
  'state.mfa.cta': 'Verify with MFA',
  'state.disabled': 'Coming soon',
  'state.notfound': 'Page not found.',
  'common.search': 'Search',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.submit': 'Submit',
  'common.confirm': 'Confirm',
  'common.more': 'More',
  'common.close': 'Close',
  'common.guests': 'Guests',
  'common.checkin': 'Check-in',
  'common.checkout': 'Check-out',
  'common.night': 'nights',
  'common.status': 'Status',
  'common.actions': 'Actions',
  'common.back': 'Back',
  'common.lang': 'Language',
  'lang.auto': 'Use browser language',
  'a11y.skip': 'Skip to content',
};

const ja: Record<DictKey, string> = {
  'nav.stay': '宿泊',
  'nav.exchange': 'ホーム交換',
  'nav.guide': 'ガイドフレンド',
  'nav.travel': '旅行商品',
  'nav.charter': 'チャーター JETPOOL',
  'nav.trips': '旅程',
  'nav.messages': 'メッセージ',
  'nav.saved': '保存',
  'nav.host': 'ホスト',
  'nav.admin': '管理',
  'nav.login': 'ログイン',
  'nav.signup': '会員登録',
  'nav.logout': 'ログアウト',
  'nav.account': 'アカウント',
  'nav.menu': 'メニュー',
  'state.loading': '読み込み中…',
  'state.empty': 'まだ項目がありません。',
  'state.error': '問題が発生しました。',
  'state.retry': '再試行',
  'state.unauth': 'このページはログインが必要です。',
  'state.forbidden': 'このページにアクセスする権限がありません。',
  'state.mfa': '管理機能には二要素認証（MFA）セッションが必要です。',
  'state.mfa.cta': 'MFAで認証する',
  'state.disabled': '近日公開',
  'state.notfound': 'ページが見つかりません。',
  'common.search': '検索',
  'common.save': '保存',
  'common.cancel': 'キャンセル',
  'common.submit': '送信',
  'common.confirm': '確認',
  'common.more': 'もっと見る',
  'common.close': '閉じる',
  'common.guests': '人数',
  'common.checkin': 'チェックイン',
  'common.checkout': 'チェックアウト',
  'common.night': '泊',
  'common.status': 'ステータス',
  'common.actions': '操作',
  'common.back': '戻る',
  'common.lang': '言語',
  'lang.auto': 'ブラウザの言語を使う',
  'a11y.skip': '本文へスキップ',
};

const zh: Record<DictKey, string> = {
  'nav.stay': '住宿',
  'nav.exchange': '房屋互换',
  'nav.guide': '向导朋友',
  'nav.travel': '旅游产品',
  'nav.charter': '包机 JETPOOL',
  'nav.trips': '行程',
  'nav.messages': '消息',
  'nav.saved': '收藏',
  'nav.host': '房东',
  'nav.admin': '管理',
  'nav.login': '登录',
  'nav.signup': '注册',
  'nav.logout': '退出登录',
  'nav.account': '账户',
  'nav.menu': '菜单',
  'state.loading': '加载中…',
  'state.empty': '还没有任何内容。',
  'state.error': '出现了问题。',
  'state.retry': '重试',
  'state.unauth': '请登录后查看此页面。',
  'state.forbidden': '您没有访问此页面的权限。',
  'state.mfa': '管理功能需要双重验证（MFA）会话。',
  'state.mfa.cta': '使用 MFA 验证',
  'state.disabled': '即将推出',
  'state.notfound': '找不到页面。',
  'common.search': '搜索',
  'common.save': '保存',
  'common.cancel': '取消',
  'common.submit': '提交',
  'common.confirm': '确认',
  'common.more': '查看更多',
  'common.close': '关闭',
  'common.guests': '人数',
  'common.checkin': '入住',
  'common.checkout': '退房',
  'common.night': '晚',
  'common.status': '状态',
  'common.actions': '操作',
  'common.back': '返回',
  'common.lang': '语言',
  'lang.auto': '使用浏览器语言',
  'a11y.skip': '跳转到正文',
};

const vi: Record<DictKey, string> = {
  'nav.stay': 'Chỗ ở',
  'nav.exchange': 'Trao đổi nhà',
  'nav.guide': 'Hướng dẫn viên',
  'nav.travel': 'Du lịch',
  'nav.charter': 'Thuê chuyến JETPOOL',
  'nav.trips': 'Chuyến đi',
  'nav.messages': 'Tin nhắn',
  'nav.saved': 'Đã lưu',
  'nav.host': 'Chủ nhà',
  'nav.admin': 'Quản trị',
  'nav.login': 'Đăng nhập',
  'nav.signup': 'Đăng ký',
  'nav.logout': 'Đăng xuất',
  'nav.account': 'Tài khoản',
  'nav.menu': 'Menu',
  'state.loading': 'Đang tải…',
  'state.empty': 'Chưa có nội dung nào.',
  'state.error': 'Đã xảy ra lỗi.',
  'state.retry': 'Thử lại',
  'state.unauth': 'Vui lòng đăng nhập để xem trang này.',
  'state.forbidden': 'Bạn không có quyền truy cập trang này.',
  'state.mfa': 'Chức năng quản trị cần phiên xác thực hai yếu tố (MFA).',
  'state.mfa.cta': 'Xác thực bằng MFA',
  'state.disabled': 'Sắp ra mắt',
  'state.notfound': 'Không tìm thấy trang.',
  'common.search': 'Tìm kiếm',
  'common.save': 'Lưu',
  'common.cancel': 'Hủy',
  'common.submit': 'Gửi',
  'common.confirm': 'Xác nhận',
  'common.more': 'Xem thêm',
  'common.close': 'Đóng',
  'common.guests': 'Số khách',
  'common.checkin': 'Nhận phòng',
  'common.checkout': 'Trả phòng',
  'common.night': 'đêm',
  'common.status': 'Trạng thái',
  'common.actions': 'Thao tác',
  'common.back': 'Quay lại',
  'common.lang': 'Ngôn ngữ',
  'lang.auto': 'Dùng ngôn ngữ của trình duyệt',
  'a11y.skip': 'Chuyển đến nội dung',
};

export const DICT: Record<Lang, Record<DictKey, string>> = { ko, en, ja, zh, vi };
