/** Status dictionary (data only — rendered by components/ui/status.tsx StatusPill). */
export type Tone = 'ok' | 'warn' | 'danger' | 'info' | 'neutral';

/**
 * FSM state → tone + localized label (ko, en). Covers every status CHECK enum in packages/db/migrations
 * (Reservation, Exchange, GuideBooking, Payment, Refund, Settlement, Order, Departure, Dispute, Support, Compliance,
 * Integration, Verification, Account …). test/status.test.ts fails when a DB status is missing here.
 */
export const STATES: Record<string, [Tone, string, string]> = {
  // drafting / quoting
  DRAFT: ['neutral', '임시저장', 'Draft'],
  CART: ['neutral', '장바구니', 'In cart'],
  QUOTED: ['neutral', '견적', 'Quoted'],
  NEW: ['info', '신규', 'New'],
  CREATED: ['neutral', '결제 대기', 'Awaiting payment'],
  QUEUED: ['neutral', '대기열', 'Queued'],
  INCOMPLETE: ['warn', '미완료', 'Incomplete'],
  // holds & payment
  HELD: ['warn', '날짜 확보', 'Held'],
  PAYMENT_PENDING: ['warn', '결제 대기', 'Payment pending'],
  PAYMENT_FAILED: ['danger', '결제 실패', 'Payment failed'],
  AUTHORIZED: ['info', '승인 대기', 'Authorized'],
  CAPTURED: ['ok', '결제 완료', 'Captured'],
  PAID: ['ok', '결제 완료', 'Paid'],
  SUCCEEDED: ['ok', '성공', 'Succeeded'],
  CONFIRMING: ['warn', '확정 중', 'Confirming'],
  PROVIDER_PENDING: ['warn', 'PG 처리 중', 'Provider pending'],
  RECONCILED: ['ok', '대사 완료', 'Reconciled'],
  // booking lifecycle
  CONFIRMED: ['ok', '확정', 'Confirmed'],
  CHECKED_IN: ['info', '체크인', 'Checked in'],
  DEPARTED: ['info', '출발', 'Departed'],
  COMPLETED: ['ok', '완료', 'Completed'],
  FULFILLED: ['ok', '이용 완료', 'Fulfilled'],
  REDEEMED: ['ok', '사용 완료', 'Redeemed'],
  CANCELLED: ['danger', '취소', 'Cancelled'],
  CANCELED: ['danger', '취소', 'Cancelled'],
  NO_SHOW: ['danger', '노쇼', 'No-show'],
  EXPIRED: ['danger', '만료', 'Expired'],
  FAILED: ['danger', '실패', 'Failed'],
  ERROR: ['danger', '오류', 'Error'],
  // refunds & payouts
  REFUNDED: ['neutral', '환불됨', 'Refunded'],
  PARTIALLY_REFUNDED: ['neutral', '부분 환불', 'Partly refunded'],
  REFUND_PENDING: ['warn', '환불 처리 중', 'Refund pending'],
  PARTIAL: ['warn', '일부 완료', 'Partial'],
  PAYOUT_PENDING: ['warn', '지급 대기', 'Payout pending'],
  PAID_OUT: ['ok', '지급 완료', 'Paid out'],
  CARRIED_FORWARD: ['neutral', '차기 이월', 'Carried forward'],
  RELEASED: ['ok', '해제됨', 'Released'],
  SETTLED: ['ok', '정산 완료', 'Settled'],
  CALCULATED: ['info', '산정됨', 'Calculated'],
  ISSUED: ['ok', '발행됨', 'Issued'],
  VOID: ['neutral', '무효', 'Void'],
  // exchange
  PROPOSED: ['warn', '제안됨', 'Proposed'],
  COUNTERED: ['warn', '역제안', 'Countered'],
  ACCEPTED: ['info', '수락됨', 'Accepted'],
  MUTUAL_ACCEPTED: ['info', '상호 수락', 'Mutually accepted'],
  VERIFICATION_PENDING: ['warn', '검증 진행 중', 'Verification pending'],
  VERIFYING: ['warn', '검증 중', 'Verifying'],
  AGREEMENT_PENDING: ['warn', '서명 대기', 'Awaiting signatures'],
  PARTIALLY_SIGNED: ['warn', '한쪽 서명 완료', 'Partly signed'],
  SIGNED: ['ok', '서명 완료', 'Signed'],
  AWAITING_PARTY: ['warn', '상대방 대기', 'Awaiting other party'],
  WITHDRAWN: ['neutral', '철회됨', 'Withdrawn'],
  SUPERSEDED: ['neutral', '대체됨', 'Superseded'],
  IN_PROGRESS: ['info', '진행 중', 'In progress'],
  DECLINED: ['danger', '거절', 'Declined'],
  // guide requests
  REQUESTED: ['warn', '요청됨', 'Requested'],
  OPEN: ['info', '모집 중', 'Open'],
  OFFERED: ['info', '제안 도착', 'Offer received'],
  SCHEDULED: ['ok', '예정', 'Scheduled'],
  // generic workflow
  PENDING: ['warn', '대기', 'Pending'],
  PENDING_CUSTOMER: ['warn', '고객 회신 대기', 'Waiting on customer'],
  APPROVAL_PENDING: ['warn', '승인 대기', 'Awaiting approval'],
  READY: ['info', '준비됨', 'Ready'],
  APPROVED: ['ok', '승인', 'Approved'],
  APPLIED: ['ok', '적용됨', 'Applied'],
  DONE: ['ok', '완료', 'Done'],
  PROCESSING: ['warn', '처리 중', 'Processing'],
  RUNNING: ['info', '실행 중', 'Running'],
  UPLOADING: ['info', '업로드 중', 'Uploading'],
  SENT: ['ok', '발송됨', 'Sent'],
  SYNCED: ['ok', '동기화됨', 'Synced'],
  REJECTED: ['danger', '반려', 'Rejected'],
  SUBMITTED: ['warn', '제출됨', 'Submitted'],
  IN_REVIEW: ['warn', '심사 중', 'In review'],
  UNDER_REVIEW: ['warn', '심사 중', 'In review'],
  REVIEW: ['warn', '검토 필요', 'Needs review'],
  REVIEWED: ['info', '검토 완료', 'Reviewed'],
  NEEDS_INFO: ['warn', '보완 요청', 'Needs info'],
  // publication & visibility
  PUBLISHED: ['ok', '게시됨', 'Published'],
  UNPUBLISHED: ['neutral', '비공개', 'Unpublished'],
  UNLISTED: ['neutral', '목록 비공개', 'Unlisted'],
  HIDDEN: ['neutral', '비공개', 'Hidden'],
  ARCHIVED: ['neutral', '보관됨', 'Archived'],
  RETIRED: ['neutral', '종료됨', 'Retired'],
  REMOVED: ['neutral', '삭제됨', 'Removed'],
  DELETED: ['neutral', '삭제됨', 'Deleted'],
  // accounts & access
  SUSPENDED: ['danger', '정지', 'Suspended'],
  RESTRICTED: ['warn', '제한됨', 'Restricted'],
  LOCKED: ['danger', '잠김', 'Locked'],
  REVOKED: ['neutral', '해지됨', 'Revoked'],
  DISABLED: ['neutral', '사용 안 함', 'Disabled'],
  ACTIVE: ['ok', '활성', 'Active'],
  INACTIVE: ['neutral', '비활성', 'Inactive'],
  PAUSED: ['neutral', '일시 중지', 'Paused'],
  PENDING_DELETION: ['warn', '탈퇴 처리 중', 'Deletion pending'],
  UNVERIFIED: ['neutral', '미인증', 'Unverified'],
  VERIFIED: ['ok', '인증 완료', 'Verified'],
  // availability & compliance
  AVAILABLE: ['ok', '예약 가능', 'Available'],
  UNAVAILABLE: ['neutral', '예약 불가', 'Unavailable'],
  ALLOW: ['ok', '예약 가능', 'Allowed'],
  DENY: ['danger', '예약 차단', 'Denied'],
  DENIED: ['danger', '예약 차단', 'Denied'],
  PASS: ['ok', '적합', 'Pass'],
  PASSED: ['ok', '적합', 'Pass'],
  FAIL: ['danger', '부적합', 'Fail'],
  BLOCKED: ['danger', '차단', 'Blocked'],
  ELIGIBLE: ['ok', '자격 충족', 'Eligible'],
  INELIGIBLE: ['danger', '자격 미달', 'Ineligible'],
  QUALIFIED: ['ok', '자격 확인', 'Qualified'],
  // travel departures & charter leads
  GUARANTEED: ['ok', '출발 확정', 'Guaranteed'],
  CLOSED: ['neutral', '마감', 'Closed'],
  CONTACTED: ['info', '연락 완료', 'Contacted'],
  CONVERTED: ['ok', '전환됨', 'Converted'],
  // disputes, support, incidents, moderation
  TRIAGED: ['info', '분류 완료', 'Triaged'],
  INVESTIGATING: ['warn', '조사 중', 'Investigating'],
  ACKNOWLEDGED: ['info', '접수 확인', 'Acknowledged'],
  ACTIONED: ['ok', '조치 완료', 'Actioned'],
  MITIGATED: ['info', '완화됨', 'Mitigated'],
  POSTMORTEM_DONE: ['ok', '사후 분석 완료', 'Postmortem done'],
  RESOLVED: ['ok', '해결', 'Resolved'],
  UPHELD: ['ok', '인용', 'Upheld'],
  DISMISSED: ['neutral', '기각', 'Dismissed'],
  FALSE_POSITIVE: ['neutral', '오탐', 'False positive'],
  SUPPRESSED: ['neutral', '숨김 처리', 'Suppressed'],
  ESCALATED: ['danger', '상위 이관', 'Escalated'],
  DISPUTED: ['danger', '분쟁', 'Disputed'],
  // flags & devices
  ON: ['ok', '켜짐', 'On'],
  OFF: ['neutral', '꺼짐', 'Off'],
  CURRENT: ['info', '현재 기기', 'This device'],
};

