primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  min_machines_running = 2

[[http_service.checks]]
  interval = "15s"
  timeout = "5s"
  grace_period = "30s"
  method = "GET"
  path = "/"

[[vm]]
  size = "shared-cpu-2x"
  memory = "1gb"
