#!/usr/bin/env node
// DEV/demo seed: applies data/media/assignments.json (generated by scripts/legacy/assign.mjs) to the database.
// Refuses NODE_ENV=production. seed-dev.mjs runs it automatically at the end when the assignments file exists, so every
// seed path (scripts/dev-up.sh, scripts/pages/record.sh, `node packages/db/seed-dev.mjs`) picks it up; it also runs alone:
//
//   node packages/db/seed-media.mjs [--assignments data/media/assignments.json]
//
// What it writes (deterministic ids, one transaction, idempotent — a re-run with the same assignments changes nothing):
//  - media_assets rows (visibility PUBLIC, status READY, moderation APPROVED, public_url /photos/… or /legacy/…, served
//    width/height/bytes/sha256): one shared CMS row per used medium (all 273 legacy wontc.co.kr media + CMS photos), and
//    per-entity rows for stays (PROPERTY, owned by the host), travel products (TRAVEL_PRODUCT) and guides (GUIDE)
//  - property_media of every seeded stay: 5 real photos (seed-owned links to the old postcard art are replaced; photos a
//    host uploaded are kept) + a search-projection outbox event when a stay's photo list changed
//  - travel_products.media_ids (while empty or seed-owned), the past WONT tour products (ARCHIVED; the recruiting one
//    PUBLISHED without departures), user_profiles.avatar_media_id of every seeded person — host, guide, traveller —
//    with an openly-licensed real portrait standing in for the persona (AVATAR; only while empty or seed-owned)
//  - the migrated wontc.co.kr CMS entries (PAGE / STORY / LEGACY_CONTENT + PAGE brand-archive) with cms_external_refs
//    (LEGACY_WONT); seed-dev's destinations / stories / pages get real covers where theirs is generated art
//  - seo_redirects legacy path → new path (exact matches approved)
// Never overwrites edited data: CMS rows refresh only while unedited (updated_at = created_at) and seed-owned; curated
// fields only replace generated placeholders (/art/…, /placeholder/…) or this seed's own previous values.
import pg from 'pg';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const DEFAULT_ASSIGNMENTS = path.resolve(HERE, '../../data/media/assignments.json');

const uid = (name) => {
  const h = createHash('sha256').update(`jetpool-seed:${name}`).digest('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`;
};
const sha256 = (s) => createHash('sha256').update(s).digest('hex');
const J = (v) => JSON.stringify(v);
/** key-order independent JSON (jsonb returns keys in its own order) — for "did anything change?" comparisons */
const canon = (v) => {
  if (v === null || typeof v !== 'object') return JSON.stringify(v);
  if (Array.isArray(v)) return `[${v.map(canon).join(',')}]`;
  return `{${Object.keys(v).filter((k) => v[k] !== undefined).sort().map((k) => `${JSON.stringify(k)}:${canon(v[k])}`).join(',')}}`;
};
const isPlaceholder = (u) => !u || /^\/(art|placeholder)\//.test(String(u));
/** media rows written by a seed (this one, seed-dev's postcard art, seed-legacy) — anything else belongs to a user */
const SEED_OWNED_SQL = (col) => `(${col} LIKE 'seed-media/%' OR ${col} LIKE 'seed/%' OR ${col} LIKE 'legacy/wont/%')`;

export async function seedMedia({ connectionString, assignmentsPath = DEFAULT_ASSIGNMENTS, log = (m) => console.log(`[seed-media] ${m}`) } = {}) {
  if (process.env.NODE_ENV === 'production') throw new Error('seed-media refuses to run with NODE_ENV=production');
  if (!existsSync(assignmentsPath)) {
    log(`no assignments at ${assignmentsPath} — nothing to do (run: node scripts/legacy/assign.mjs)`);
    return { skipped: true };
  }
  const A = JSON.parse(readFileSync(assignmentsPath, 'utf8'));
  if (A.version !== 1) throw new Error(`unsupported assignments version ${A.version}`);
  const SEEDED_AT = new Date(A.generatedFrom?.catalogGeneratedAt ?? '2026-10-08T00:00:00Z').toISOString();
  const db = new pg.Client({ connectionString: connectionString ?? process.env.DATABASE_URL ?? 'postgres://postgres@localhost:5432/jetpool' });
  await db.connect();
  const q = (text, params = []) => db.query(text, params);
  const one = async (text, params = []) => (await db.query(text, params)).rows[0] ?? null;
  const counts = {};
  const bump = (k, n = 1) => {
    if (n) counts[k] = (counts[k] ?? 0) + n;
  };
  const missing = [];

  const asset = (url) => {
    const a = A.assets[url];
    if (!a) throw new Error(`assignments has no asset facts for ${url}`);
    return a;
  };
  /** Upsert one media_assets row; returns its id. Rows not created by this seed are never modified. */
  async function media(id, storageKey, url, purpose, ownerId) {
    const a = asset(url);
    const r = await q(
      `INSERT INTO media_assets(id, owner_id, storage_key, public_url, purpose, visibility, mime_type, byte_size, sha256, width, height, status, moderation_status, ready_at, created_at)
       VALUES ($1,$2,$3,$4,$5,'PUBLIC',$6,$7,$8,$9,$10,'READY','APPROVED',$11,$11)
       ON CONFLICT (id) DO UPDATE SET owner_id = EXCLUDED.owner_id, public_url = EXCLUDED.public_url, purpose = EXCLUDED.purpose, visibility = 'PUBLIC',
              mime_type = EXCLUDED.mime_type, byte_size = EXCLUDED.byte_size, sha256 = EXCLUDED.sha256, width = EXCLUDED.width, height = EXCLUDED.height,
              status = 'READY', moderation_status = 'APPROVED'
        WHERE media_assets.storage_key LIKE 'seed-media/%'
          AND (media_assets.owner_id, media_assets.public_url, media_assets.purpose, media_assets.visibility, media_assets.mime_type, media_assets.byte_size,
               media_assets.sha256, media_assets.width, media_assets.height, media_assets.status, media_assets.moderation_status)
              IS DISTINCT FROM (EXCLUDED.owner_id, EXCLUDED.public_url, EXCLUDED.purpose, 'PUBLIC', EXCLUDED.mime_type, EXCLUDED.byte_size,
               EXCLUDED.sha256, EXCLUDED.width, EXCLUDED.height, 'READY', 'APPROVED')
       RETURNING (xmax = 0) AS inserted`,
      [id, ownerId ?? null, storageKey, url, purpose, a.mime, Math.max(1, a.bytes), a.sha256, a.width, a.height, SEEDED_AT],
    );
    if (r.rows[0]) bump(r.rows[0].inserted ? 'media_assets' : 'media_assets (refreshed)');
    return id;
  }
  const sharedId = (url) => uid(`media:${asset(url).kind}:${asset(url).sha12}`);
  const shared = (url) => media(sharedId(url), `seed-media/${asset(url).kind}/${asset(url).sha12}`, url, 'CMS', null);

  try {
    await q('BEGIN');
    const admin = (await one(`SELECT id FROM users WHERE id = $1`, [uid('user:admin')]))?.id ?? null;
    const supplierUser = (await one(`SELECT id FROM users WHERE id = $1`, [uid('user:supplier')]))?.id ?? null;
    const supplier = (await one(`SELECT id FROM suppliers WHERE id = $1`, [uid('supplier:wont')]))?.id ?? null;

    // ---- shared CMS media: every legacy medium (all 273 — the brand archive shows them) and every photo used by CMS/home
    const sharedUrls = Object.entries(A.assets)
      .filter(([, a]) => a.kind === 'legacy' || a.uses.some((u) => !/^(stay|product|guide):/.test(u)))
      .map(([u]) => u);
    for (const u of sharedUrls) await shared(u);

    // ---- stays: 5 real photos each, replacing seed-owned links
    for (const [slug, s] of Object.entries(A.stays)) {
      const prop = await one(`SELECT id, host_id FROM properties WHERE id = $1`, [s.propertyId]);
      if (!prop) {
        missing.push(`property ${slug}`);
        continue;
      }
      const ids = [];
      for (const [i, ph] of s.photos.entries()) ids.push(await media(uid(`media:real:${slug}:${i}`), `seed-media/property/${slug}/${i}`, ph.url, 'PROPERTY', prop.host_id));
      bump(
        'property_media (seed links replaced)',
        (await q(
          `DELETE FROM property_media pm USING media_assets m
            WHERE pm.property_id = $1 AND m.id = pm.media_id AND ${SEED_OWNED_SQL('m.storage_key')} AND NOT (pm.media_id = ANY($2::uuid[]))`,
          [prop.id, ids],
        )).rowCount,
      );
      for (const [i, ph] of s.photos.entries()) {
        const r = await q(
          `INSERT INTO property_media(property_id, media_id, sort_order, caption) VALUES ($1,$2,$3,$4)
           ON CONFLICT (property_id, media_id) DO UPDATE SET sort_order = EXCLUDED.sort_order, caption = EXCLUDED.caption
            WHERE property_media.sort_order <> EXCLUDED.sort_order OR property_media.caption IS DISTINCT FROM EXCLUDED.caption`,
          [prop.id, ids[i], i, ph.caption],
        );
        bump('property_media', r.rowCount);
      }
      // search projection (PLAT-01): one deterministic event per distinct photo list → the worker re-projects the stay
      const fp = (await one(
        `SELECT string_agg(m.public_url, ',' ORDER BY pm.sort_order, m.id) AS photos FROM property_media pm JOIN media_assets m ON m.id = pm.media_id WHERE pm.property_id = $1`,
        [prop.id],
      ))?.photos;
      bump(
        'outbox_events (search projection)',
        (await q(
          `INSERT INTO outbox_events(id, aggregate_type, aggregate_id, event_type, payload, correlation_id) VALUES ($1,'property',$2,'property.seed_refreshed',$3,'seed-media') ON CONFLICT DO NOTHING`,
          [uid(`outbox:search-media:${prop.id}:${sha256(fp ?? '')}`), prop.id, J({ propertyId: prop.id, source: 'seed-media' })],
        )).rowCount,
      );
    }

    // ---- guides: the scene photo of the guide's city/interest (their cover; the web reads it from media-map.json)
    for (const [key, g] of Object.entries(A.guides)) {
      if (!(await one(`SELECT 1 FROM guide_profiles WHERE user_id = $1`, [g.userId]))) {
        missing.push(`guide ${key}`);
        continue;
      }
      await media(uid(`media:guide:${key}`), `seed-media/guide/${key}`, g.url, 'GUIDE', g.userId);
    }

    // ---- people: a real licensed portrait as the profile photo of every seeded host / guide / traveller
    // (a stand-in for the persona, never a photo of them). Only written while the profile has no avatar of its own.
    for (const [key, p] of Object.entries(A.people ?? {})) {
      if (!(await one(`SELECT 1 FROM user_profiles WHERE user_id = $1`, [p.userId]))) {
        missing.push(`person ${key}`);
        continue;
      }
      const mid = await media(uid(`media:person:${key}`), `seed-media/person/${key}`, p.url, 'AVATAR', p.userId);
      bump(
        'profile photos (avatar_media_id)',
        (await q(
          `UPDATE user_profiles SET avatar_media_id = $2
            WHERE user_id = $1 AND avatar_media_id IS DISTINCT FROM $2
              AND (avatar_media_id IS NULL OR EXISTS (SELECT 1 FROM media_assets m WHERE m.id = user_profiles.avatar_media_id AND ${SEED_OWNED_SQL('m.storage_key')}))`,
          [p.userId, mid],
        )).rowCount,
      );
    }

    // ---- travel products: theme photos (media_ids replaced only while empty or entirely seed-owned)
    async function productMedia(productId, slug, urls) {
      const ids = [];
      for (const [i, u] of urls.entries()) ids.push(await media(uid(`media:product:${slug}:${i}`), `seed-media/product/${slug}/${i}`, u, 'TRAVEL_PRODUCT', supplierUser));
      bump(
        'travel_products (media_ids)',
        (await q(
          `UPDATE travel_products SET media_ids = $2::uuid[]
            WHERE id = $1 AND media_ids IS DISTINCT FROM $2::uuid[]
              AND NOT EXISTS (SELECT 1 FROM unnest(media_ids) x LEFT JOIN media_assets m ON m.id = x WHERE m.id IS NULL OR NOT ${SEED_OWNED_SQL('m.storage_key')})`,
          [productId, ids],
        )).rowCount,
      );
    }
    for (const [slug, p] of Object.entries(A.products)) {
      if (!(await one(`SELECT 1 FROM travel_products WHERE id = $1`, [p.productId]))) {
        missing.push(`product ${slug}`);
        continue;
      }
      await productMedia(p.productId, slug, p.urls);
    }
    // past WONT tour products (the recruiting one PUBLISHED without departures — consultation only)
    if (supplier) {
      for (const p of A.legacyProducts) {
        const created = p.status === 'PUBLISHED' ? '2025-04-01T10:00:00+09:00' : '2024-01-01T10:00:00+09:00';
        bump(
          'travel_products (WONT legacy)',
          (await q(
            `INSERT INTO travel_products(id, supplier_id, type, slug, title, summary, description, city, country, duration_minutes, base_price_minor, currency, status, cancellation_terms, created_at, updated_at)
             VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'KRW',$12,$13,$14,$14) ON CONFLICT DO NOTHING`,
            [p.productId, supplier, p.type, p.slug, p.title, p.summary, p.description, p.city, p.country, p.durationMinutes, p.basePriceMinor, p.status,
              J({ note: p.status === 'PUBLISHED' ? '출발 일정이 확정되면 상담 후 개별 안내 (현재 예약·결제 없음)' : '진행이 끝난 원여행클럽 프로그램 — 예약 불가', legacy: { system: 'LEGACY_WONT', path: p.legacyPath } }),
              created],
          )).rowCount,
        );
        if (await one(`SELECT 1 FROM travel_products WHERE id = $1`, [p.productId])) await productMedia(p.productId, p.slug, p.media);
      }
    } else missing.push('supplier WONT Travel Club Tours (legacy products skipped)');

    // ---- migrated wontc.co.kr pages → CMS entries
    for (const e of A.cms) {
      const heroId = e.heroUrl ? sharedId(e.heroUrl) : null;
      const data = { ...e.data, seedMedia: { hash: sha256(J([e.title, e.summary, e.bodyMd, e.seo, e.data, heroId])), source: 'scripts/legacy/assign.mjs' } };
      const r = await one(
        `INSERT INTO cms_entries(id, entry_type, slug, locale, title, summary, body_md, hero_media_id, seo, data, status, published_at, author_id, created_at, updated_at)
         VALUES ($1,$2,$3,'ko-KR',$4,$5,$6,$7,$8,$9,'PUBLISHED',$10,$11,$10,$10)
         ON CONFLICT (entry_type, slug, locale) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, body_md = EXCLUDED.body_md,
                hero_media_id = EXCLUDED.hero_media_id, seo = EXCLUDED.seo, data = EXCLUDED.data
          WHERE cms_entries.data ? 'seedMedia' AND cms_entries.updated_at = cms_entries.created_at
            AND cms_entries.data->'seedMedia'->>'hash' IS DISTINCT FROM EXCLUDED.data->'seedMedia'->>'hash'
         RETURNING id, (xmax = 0) AS inserted`,
        [uid(`cms:${e.type}:${e.slug}`), e.type, e.slug, e.title, e.summary, e.bodyMd, heroId, J(e.seo), J(data), e.publishedAt, admin],
      );
      if (r) bump(r.inserted ? 'cms_entries' : 'cms_entries (refreshed)');
      const row = await one(`SELECT id, data ? 'seedMedia' AS owned FROM cms_entries WHERE entry_type = $1 AND slug = $2 AND locale = 'ko-KR'`, [e.type, e.slug]);
      if (!row?.owned) {
        missing.push(`cms ${e.type}:${e.slug} (slug used by another entry)`);
        continue;
      }
      bump(
        'cms_external_refs',
        (await q(`INSERT INTO cms_external_refs(entry_id, system, external_id, external_url, source_updated_at) VALUES ($1,'LEGACY_WONT',$2,$3,$4) ON CONFLICT DO NOTHING`, [
          row.id, e.externalId.slice(0, 300), (e.legacyUrl ?? '').slice(0, 2000) || null, SEEDED_AT,
        ])).rowCount,
      );
    }

    // ---- seed-dev's curated entries: real covers instead of generated art (previous values kept in data.seedMedia)
    async function curate(type, slug, apply) {
      const row = await one(`SELECT id, data, seo, hero_media_id FROM cms_entries WHERE entry_type = $1 AND slug = $2 AND locale = 'ko-KR'`, [type, slug]);
      if (!row) {
        missing.push(`cms ${type}:${slug}`);
        return;
      }
      const data = structuredClone(row.data ?? {});
      const seo = structuredClone(row.seo ?? {});
      const prev = data.seedMedia ?? {};
      const mine = { ...(prev.values ?? {}) };
      const previous = { ...(prev.previous ?? {}) };
      /** set obj[key] = value when the current value is generated art / missing, or this seed's own earlier value */
      const own = (obj, key, value, tag) => {
        const cur = obj[key];
        const ours = mine[tag] !== undefined && canon(cur) === canon(mine[tag]);
        const free = cur === undefined || cur === null || (typeof cur === 'string' && isPlaceholder(cur)) || (Array.isArray(cur) && !cur.length);
        if (!ours && !free) return;
        if (!ours && !(tag in previous)) previous[tag] = cur ?? null;
        obj[key] = value;
        mine[tag] = value;
      };
      const heroUrl = apply({ data, seo, own });
      data.seedMedia = { values: mine, previous, source: 'scripts/legacy/assign.mjs' };
      const heroId = heroUrl ? sharedId(heroUrl) : null;
      const heroOk = heroId && (!row.hero_media_id || (await one(`SELECT 1 FROM media_assets WHERE id = $1 AND ${SEED_OWNED_SQL('storage_key')}`, [row.hero_media_id])));
      const newHero = heroOk ? heroId : row.hero_media_id;
      if (canon(data) === canon(row.data ?? {}) && canon(seo) === canon(row.seo ?? {}) && newHero === row.hero_media_id) return;
      const r = await q(`UPDATE cms_entries SET data = $2, seo = $3, hero_media_id = $4 WHERE id = $1 AND data = $5::jsonb AND seo = $6::jsonb`, [row.id, J(data), J(seo), newHero, J(row.data), J(row.seo ?? {})]);
      bump(`curated ${type}`, r.rowCount);
    }
    const og = (seo, own, url) => {
      seo.og = seo.og ?? {};
      own(seo.og, 'image', url, 'ogImage');
    };
    for (const [slug, d] of Object.entries(A.destinations)) {
      await curate('DESTINATION', slug, ({ data, seo, own }) => {
        own(data, 'coverUrl', d.coverUrl, 'coverUrl');
        own(data, 'heroUrl', d.coverUrl, 'heroUrl');
        own(data, 'gallery', d.gallery, 'gallery');
        og(seo, own, d.coverUrl);
        return d.coverUrl;
      });
    }
    for (const [slug, s] of Object.entries(A.stories)) {
      await curate('STORY', slug, ({ data, seo, own }) => {
        own(data, 'coverUrl', s.coverUrl, 'coverUrl');
        own(data, 'heroUrl', s.coverUrl, 'heroUrl');
        og(seo, own, s.coverUrl);
        return s.coverUrl;
      });
    }
    const ch = A.pages['jetpool-charter'];
    if (ch) {
      await curate('PAGE', 'jetpool-charter', ({ data, seo, own }) => {
        own(data, 'heroUrl', ch.heroUrl, 'heroUrl');
        own(data, 'coverUrl', ch.heroUrl, 'coverUrl');
        own(data, 'gallery', ch.gallery, 'gallery');
        og(seo, own, ch.heroUrl);
        return ch.heroUrl;
      });
    }
    const home = A.pages['wont-home'];
    if (home) {
      await curate('PAGE', 'wont-home', ({ data, own }) => {
        for (const b of data.blocks ?? []) if (home.blocks[b.key]) own(b, 'imageUrl', home.blocks[b.key], `block:${b.key}`);
        own(data, 'heroUrl', home.blocks['month-exchange'], 'heroUrl');
        return home.blocks['month-exchange'];
      });
    }

    // ---- legacy URL redirects (exact matches approved; never overrides an admin decision)
    for (const r of A.redirects) {
      const replaces = A.replacesRedirects?.[r.legacyPath] ?? null;
      bump(
        'seo_redirects',
        (await q(
          `INSERT INTO seo_redirects(legacy_path, target_path, status_code, approved, source) VALUES ($1,$2,$3,$4,'LEGACY_WONT')
           ON CONFLICT (legacy_path) DO UPDATE SET target_path = EXCLUDED.target_path, status_code = EXCLUDED.status_code, approved = EXCLUDED.approved,
                  source = 'LEGACY_WONT', updated_at = seo_redirects.created_at
            WHERE (seo_redirects.target_path, seo_redirects.status_code, seo_redirects.approved) IS DISTINCT FROM (EXCLUDED.target_path, EXCLUDED.status_code, EXCLUDED.approved)
              AND ((seo_redirects.source = 'LEGACY_WONT' AND seo_redirects.hits = 0 AND seo_redirects.updated_at = seo_redirects.created_at)
                   OR (seo_redirects.source IS NULL AND seo_redirects.target_path = $5::text))`,
          [r.legacyPath, r.targetPath, r.statusCode ?? 301, r.approved, replaces],
        )).rowCount,
      );
    }

    await q('COMMIT');
  } catch (err) {
    await q('ROLLBACK').catch(() => {});
    throw err;
  } finally {
    await db.end();
  }
  const summary = Object.entries(counts).map(([k, v]) => `${k}+${v}`).join(', ');
  log(summary ? `applied ${path.relative(process.cwd(), assignmentsPath) || assignmentsPath}: ${summary}` : 'nothing new (media already applied)');
  if (missing.length) log(`skipped (not in this database): ${missing.join('; ')}`);
  return { counts, missing };
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href;
if (isMain) {
  if (process.env.NODE_ENV === 'production') {
    console.error('seed-media refuses to run with NODE_ENV=production');
    process.exit(1);
  }
  const argv = process.argv.slice(2);
  const i = argv.indexOf('--assignments');
  const assignmentsPath = i >= 0 && argv[i + 1] ? path.resolve(process.env.INIT_CWD || process.cwd(), argv[i + 1]) : DEFAULT_ASSIGNMENTS;
  seedMedia({ assignmentsPath }).catch((err) => {
    console.error(`[seed-media] failed, nothing written: ${err.stack ?? err.message}`);
    process.exitCode = 1;
  });
}
